### ISSUE TITLE
HMCan: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nitinnarwade** [BoevaLab/HMCan#1]
I am trying to run **HMCan v1.43 (GitHub version)** by following the instructions given in the readme file and I have ended up with this generalized error **Segmentation fault (core dumped)**. I don’t know why I am getting this error.

Here is the configuration file that I am using for running HMCan:

`format bam`
`GCIndex /program/hmcan/data/GC_profile_25KbWindow_Mapp76_hg19.cnp`
`genomePath hg19-chrs`
`minLength 100`
`medLength 250`
`maxLength 400`
`smallBinLength 50`
`largeBinLength 25000`
`calculateEmpiricalPvalue True`
`pvalueThreshold 0.05`
`mergeDistance 200`
`iterationThreshold 2`
`finalThreshold 0.1`
`maxIter 20`
`PosteriorProb 0.99`
`PrintWig False`
`PrintPosterior True`
`blackListFile hg19-blacklist.bed`
`PrintBedGraph False`
`CallPeaks True`
`pairedEnds False`
`RemoveDuplicates False`

Could you please help me out what's wrong with this.

Thank you.
Nitin

**Comment by AshoorH** [comment]
Hi Nitin, 

 Could you please also share with me the log file (HMCan output)  and the command you used to be able to to troubleshoot the issue better? 

Thanks
Haitham

**Comment by nitinnarwade** [comment]
Hi Haitham,

Thank you for your reply.

The output folder has not yet generated. Here is the log, perhaps it would help you to track the step.

`HMCan v1.43 : detection of histone modifications in normal and cancer ChIP-seq datasets`
`Reading chip....`
`Kept 35465400 reads`
`Reading control....`
`Kept 35264849 reads`
`Segmentation fault (core dumped)`

Thank you.
Nitin

**Comment by AshoorH** [comment]
Hi Nitin, 

Could you provide me with an example small dataset that produce 
the segmentation fault so I can try to trace the error? 

Thanks
Haitham
